name: CI

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:

env:
  JAVA_VERSION: 17
  JAVA_DISTRO: temurin
  DOCKER_HUB_IMAGE_NAME: marcelcoding/luna

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Lint with Gradle
        run: ./gradlew checkstyleMain checkstyleTest spotbugsMain spotbugsTest pmdMain pmdTest --stacktrace --no-daemon --refresh-dependencies

      #- name: Annotate Checkstyle Issues
      #  uses: jwgmeligmeyling/checkstyle-github-action@master
      #  with:
      #    path: '**/build/reports/checkstyle/*.xml'

      #- name: Annotate SpotBugs Issues
      #  uses: jwgmeligmeyling/spotbugs-github-action@master
      #  with:
      #    path: '**/build/reports/spotbugs/*.xml'

      #- name: Annotate PMD Issues
      #  uses: jwgmeligmeyling/pmd-github-action@master
      #  with:
      #    path: '**/build/reports/pmd/*.xml'

  nohttp:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: NoHttp with Gradle
        run: ./gradlew nohttp --stacktrace --no-daemon --refresh-dependencies

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ 17 ]
        java-distro: [ temurin, zulu ]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ matrix.java-distro }}-${{ matrix.java-version }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-${{ matrix.java-distro }}-${{ matrix.java-version }}-

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          distribution: ${{ matrix.java-distro }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests with Gradle
        run: ./gradlew test --stacktrace --no-daemon --refresh-dependencies

  build:
    needs: [ lint, nohttp, test ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew :luna-main:shadowJar :luna-main:assemble --stacktrace --no-daemon --refresh-dependencies

      - uses: actions/upload-artifact@v2
        with:
          name: luna
          path: luna-main/build/libs

  docker:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      packages: write

    #    strategy:
    #      matrix:
    #        jvm-impl: [ hotspot, openj9 ]
    #        include:
    #          - jvm-impl: hotspot
    #            platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
    #          - jvm-impl: openj9
    #            platforms: linux/amd64 #,linux/arm64/v8

    steps:
      - uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          tag-edge: true
          images: |
            ${{ env.DOCKER_HUB_IMAGE_NAME }}
            ghcr.io/${{ github.repository }}
          tags: |
            type=edge
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - uses: docker/setup-qemu-action@v1
        if: matrix.platforms != 'linux/amd64'

      - uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.jvm-impl }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ matrix.jvm-impl }}-

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - uses: actions/download-artifact@v2
        with:
          name: luna

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.github-actions
          platforms: linux/amd64,linux/arm64/v8 #${{ matrix.platforms }} linux/arm/v7,
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            JVM_VERSION=${{ env.JAVA_VERSION }}
          # JVM_IMPL=${{ matrix.jvm-impl }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

#      - name: Inspect image
#        if: github.event_name != 'pull_request'
#        run: |
#          docker pull ${{ env.DOCKER_HUB_IMAGE_NAME }}:${{ steps.docker_meta.outputs.version }}
#          docker image inspect ${{ env.DOCKER_HUB_IMAGE_NAME }}:${{ steps.docker_meta.outputs.version }}
#
#      - name: Check manifest
#        if: github.event_name != 'pull_request'
#        run: |
#          docker buildx imagetools inspect ${{ env.DOCKER_HUB_IMAGE_NAME }}:${{ steps.docker_meta.outputs.version }}
#          docker buildx imagetools inspect ghcr.io/${{ github.repository }}:${{ steps.docker_meta.outputs.version }}
